"""Generate idempotent PostgreSQL seed SQL from generated data."""

from __future__ import annotations

from datetime import datetime, timezone


def generate_sql(
    students: list[dict],
    tutors: list[dict],
    exams: list[dict],
    all_scores: list[dict],
    all_ai_results: list[dict],
    objections: list[dict],
    plagiarism_flags: list[dict],
    chat_messages: list[dict],
) -> str:
    """Generate idempotent SQL insert script."""
    lines = [
        "-- ExamPen seed data (auto-generated, idempotent)",
        "-- Generated by scripts/seed_data.py",
        f"-- Timestamp: {datetime.now(timezone.utc).isoformat()}",
        "", "BEGIN;", "",
    ]
    _add_cleanup(lines, students, tutors, exams, all_scores,
                 all_ai_results, objections, plagiarism_flags, chat_messages)
    lines.append("")
    _add_students(lines, students)
    _add_tutors(lines, tutors)
    _add_exams(lines, exams)
    _add_ai_results(lines, all_ai_results)
    _add_scores(lines, all_scores)
    _add_objections(lines, objections)
    _add_plagiarism(lines, plagiarism_flags)
    _add_chat(lines, chat_messages)
    lines.extend(["", "COMMIT;", ""])
    return "\n".join(lines)


def _id_list(items: list[dict]) -> str:
    return ",".join(f"'{i['id']}'" for i in items)


def _add_cleanup(
    lines: list[str], students, tutors, exams, scores,
    ai_results, objections, plag_flags, chat_msgs,
) -> None:
    lines.append("-- Clean existing seed data (idempotent)")
    for label, items, table in [
        ("chat", chat_msgs, "chat_messages"),
        ("plagiarism", plag_flags, "plagiarism_flags"),
        ("objections", objections, "objections"),
        ("scores", scores, "scores"),
        ("AI results", ai_results, "ai_results"),
        ("exams", exams, "exams"),
        ("students", students, "students"),
        ("tutors", tutors, "tutors"),
    ]:
        if items:
            lines.append(f"DELETE FROM {table} WHERE id IN ({_id_list(items)});")


def _add_students(lines: list[str], students: list[dict]) -> None:
    lines.append("\n-- Students")
    for s in students:
        lines.append(
            f"INSERT INTO students (id, stoody_user_id, first_name, last_name, "
            f"roll_number, class_section, email) VALUES "
            f"('{s['id']}', '{s['stoody_user_id']}', '{s['first_name']}', "
            f"'{s['last_name']}', '{s['roll_number']}', '{s['class_section']}', "
            f"'{s['email']}') ON CONFLICT (id) DO NOTHING;"
        )


def _add_tutors(lines: list[str], tutors: list[dict]) -> None:
    lines.append("\n-- Tutors")
    for t in tutors:
        lines.append(
            f"INSERT INTO tutors (id, stoody_user_id, first_name, last_name, "
            f"subject, email) VALUES "
            f"('{t['id']}', '{t['stoody_user_id']}', '{t['first_name']}', "
            f"'{t['last_name']}', '{t['subject']}', '{t['email']}') "
            f"ON CONFLICT (id) DO NOTHING;"
        )


def _add_exams(lines: list[str], exams: list[dict]) -> None:
    lines.append("\n-- Exams")
    for e in exams:
        variants = "'{" + ",".join(e["variants"]) + "}'"
        lines.append(
            f"INSERT INTO exams (id, title, subject, class_section, tutor_id, "
            f"duration_minutes, total_marks, questions_count, variants, state, "
            f"created_at, scheduled_at) VALUES "
            f"('{e['id']}', '{e['title']}', '{e['subject']}', "
            f"'{e['class_section']}', '{e['tutor_id']}', {e['duration_minutes']}, "
            f"{e['total_marks']}, {e['questions_count']}, {variants}, "
            f"'{e['state']}', '{e['created_at']}', '{e['scheduled_at']}') "
            f"ON CONFLICT (id) DO NOTHING;"
        )


def _add_ai_results(lines: list[str], ai_results: list[dict]) -> None:
    lines.append("\n-- AI Results (first 20; full data in JSON fixtures)")
    for r in ai_results[:20]:
        lines.append(
            f"INSERT INTO ai_results (id, student_id, exam_id, question_number, "
            f"confidence, total_ai_score, max_marks, model_version, processed_at) "
            f"VALUES ('{r['id']}', '{r['student_id']}', '{r['exam_id']}', "
            f"{r['question_number']}, {r['confidence']}, {r['total_ai_score']}, "
            f"{r['max_marks']}, '{r['model_version']}', '{r['processed_at']}') "
            f"ON CONFLICT (id) DO NOTHING;"
        )
    if len(ai_results) > 20:
        lines.append(f"-- ... {len(ai_results) - 20} more in JSON fixtures")


def _add_scores(lines: list[str], scores: list[dict]) -> None:
    lines.append("\n-- Scores (first 20; full data in JSON fixtures)")
    for s in scores[:20]:
        tv = f"{s['teacher_score']}" if s["teacher_score"] is not None else "NULL"
        ov = f"'{s['override_reason']}'" if s["override_reason"] else "NULL"
        lines.append(
            f"INSERT INTO scores (id, student_id, exam_id, question_number, "
            f"ai_score, teacher_score, final_score, max_marks, state, "
            f"override_reason, ai_result_id, created_at, updated_at) VALUES "
            f"('{s['id']}', '{s['student_id']}', '{s['exam_id']}', "
            f"{s['question_number']}, {s['ai_score']}, {tv}, "
            f"{s['final_score']}, {s['max_marks']}, '{s['state']}', "
            f"{ov}, '{s['ai_result_id']}', "
            f"'{s['created_at']}', '{s['updated_at']}') "
            f"ON CONFLICT (id) DO NOTHING;"
        )
    if len(scores) > 20:
        lines.append(f"-- ... {len(scores) - 20} more in JSON fixtures")


def _add_objections(lines: list[str], objections: list[dict]) -> None:
    lines.append("\n-- Objections")
    for o in objections:
        assigned = f"'{o['assigned_to']}'" if o["assigned_to"] else "NULL"
        resolution = f"'{o['resolution']}'" if o["resolution"] else "NULL"
        resolved = f"'{o['resolved_at']}'" if o["resolved_at"] else "NULL"
        lines.append(
            f"INSERT INTO objections (id, score_id, student_id, exam_id, "
            f"question_number, reason, state, filed_at, assigned_to, "
            f"resolution, resolved_at) VALUES "
            f"('{o['id']}', '{o['score_id']}', '{o['student_id']}', "
            f"'{o['exam_id']}', {o['question_number']}, '{o['reason']}', "
            f"'{o['state']}', '{o['filed_at']}', {assigned}, "
            f"{resolution}, {resolved}) ON CONFLICT (id) DO NOTHING;"
        )


def _add_plagiarism(lines: list[str], flags: list[dict]) -> None:
    lines.append("\n-- Plagiarism flags")
    for f in flags:
        lines.append(
            f"INSERT INTO plagiarism_flags (id, exam_id, question_number, "
            f"student_a_id, student_b_id, tfidf_cosine_similarity, "
            f"structural_similarity, composite_score, threshold, flagged, "
            f"detected_at) VALUES "
            f"('{f['id']}', '{f['exam_id']}', {f['question_number']}, "
            f"'{f['student_a_id']}', '{f['student_b_id']}', "
            f"{f['tfidf_cosine_similarity']}, {f['structural_similarity']}, "
            f"{f['composite_score']}, {f['threshold']}, {f['flagged']}, "
            f"'{f['detected_at']}') ON CONFLICT (id) DO NOTHING;"
        )


def _add_chat(lines: list[str], messages: list[dict]) -> None:
    lines.append("\n-- Chat messages")
    for m in messages:
        read_at = f"'{m['read_at']}'" if m["read_at"] else "NULL"
        lines.append(
            f"INSERT INTO chat_messages (id, thread_id, exam_id, sender_id, "
            f"sender_role, text, created_at, read_at) VALUES "
            f"('{m['id']}', '{m['thread_id']}', '{m['exam_id']}', "
            f"'{m['sender_id']}', '{m['sender_role']}', '{m['text']}', "
            f"'{m['created_at']}', {read_at}) ON CONFLICT (id) DO NOTHING;"
        )
