#!/usr/bin/env bash
# generate-mocks.sh — Generate docker-compose.mock.yml from OpenAPI specs
# Scans new-docs/api/*.openapi.yaml and creates a Prism mock service for each.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
API_DIR="$REPO_ROOT/new-docs/api"
OUTPUT="$REPO_ROOT/infra/docker-compose.mock.yml"

# Ordered port mapping (matches COMPONENT_INDEPENDENCE_MAP §4.3)
declare -A PORT_MAP=(
  [auth]=4010
  [exam-orch]=4011
  [stroke-ingest]=4012
  [score-engine]=4013
  [review]=4014
  [analytics]=4015
  [plagiarism]=4016
  [chat]=4017
  [copy-upload]=4018
  [teacher-bff]=4019
  [student-bff]=4020
  [invig-console]=4021
)

# Ordered list for deterministic output
SERVICES=(
  auth exam-orch stroke-ingest score-engine review analytics
  plagiarism chat copy-upload teacher-bff student-bff invig-console
)

if [ ! -d "$API_DIR" ]; then
  echo "ERROR: API spec directory not found: $API_DIR" >&2
  exit 1
fi

echo "Generating $OUTPUT from specs in $API_DIR ..."

cat > "$OUTPUT" << 'HEADER'
# ExamPen — Mock API Servers (auto-generated by generate-mocks.sh)
# Usage: docker compose -f infra/docker-compose.mock.yml up
# Port Mapping:
#   auth=4010  exam-orch=4011  stroke-ingest=4012  score-engine=4013
#   review=4014  analytics=4015  plagiarism=4016  chat=4017
#   copy-upload=4018  teacher-bff=4019  student-bff=4020  invig-console=4021

x-prism: &prism
  image: stoplight/prism:latest
  command: mock /spec.yaml --host 0.0.0.0 --port 4010
  healthcheck:
    test: ["CMD-SHELL", "wget -qO- http://localhost:4010/ || true"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 5s
  networks: [exampen-net]

services:
HEADER

for svc in "${SERVICES[@]}"; do
  spec_file="$API_DIR/${svc}.openapi.yaml"
  port="${PORT_MAP[$svc]}"

  if [ ! -f "$spec_file" ]; then
    echo "WARN: Spec not found, skipping: $spec_file" >&2
    continue
  fi

  cat >> "$OUTPUT" << EOF
  mock-${svc}:
    <<: *prism
    ports: ["${port}:4010"]
    volumes: [../new-docs/api/${svc}.openapi.yaml:/spec.yaml:ro]

EOF
done

cat >> "$OUTPUT" << 'FOOTER'
networks:
  exampen-net:
    driver: bridge
FOOTER

LINE_COUNT=$(wc -l < "$OUTPUT")
echo "Generated $OUTPUT (${LINE_COUNT} lines) with ${#SERVICES[@]} mock services."

if [ "$LINE_COUNT" -gt 150 ]; then
  echo "WARN: File exceeds 150-line config limit (${LINE_COUNT} lines)." >&2
fi

echo "Run: docker compose -f infra/docker-compose.mock.yml up"
