"""
PCR Solution Repository
=======================

Async MongoDB persistence for ``evalpen_solutions`` — versioned reference
solutions with cache warmup metadata.

Solutions are **versioned and append-only** at the version level.  Each
``(question_id, version)`` pair is unique.  New versions are inserted, not
updated in place.  The latest version (highest ``version`` number) is the
active reference solution.

The solution source can be ``teacher`` (manually uploaded) or ``llm``
(generated by the evaluation engine via the LLM gate on cache miss).

Cache strategy (PCR_EVAL_ENGINE_SPEC Section 5.1):
    The cache key is question-centric.  On cache hit, PCR runs compare-only
    evaluation.  On cache miss, the engine generates/refreshes a reference
    solution, stores it here, then evaluates.

Ownership Declaration
---------------------
- Writes: ``evalpen_solutions``
- Reads from: ``evalpen_questions`` (for question context)
- Never writes to: ``evalpen_submissions``, ``evalpen_answer_pages``,
  ``evalpen_detected_responses``, practice collections
- Transactional boundaries: solution version persisted atomically

References
----------
- Storage model: new-docs/architecture/PCR_EVAL_ENGINE_SPEC.md  (Section 7.5)
- Cache strategy: new-docs/architecture/PCR_EVAL_ENGINE_SPEC.md (Section 5.1)
- Failure modes: PCR-04 (practice path starts creating persistence —
  solutions may be shared, but practice does NOT create new PCR persistence)
- Test IDs:      U-EVAL-01
- API schema:    new-docs/api/eval-solutions.openapi.yaml (SolutionDetail,
  UpsertSolutionRequest)
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from motor.motor_asyncio import AsyncIOMotorDatabase
from pymongo import ASCENDING, DESCENDING, IndexModel
from pymongo.errors import DuplicateKeyError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Collection name — PCR_EVAL_ENGINE_SPEC 7.5
# ---------------------------------------------------------------------------

SOLUTIONS_COLLECTION = "evalpen_solutions"


class SolutionVersionConflictError(Exception):
    """Raised when a solution version already exists for a question.

    Solutions are versioned and append-only.  If the same
    ``(question_id, version)`` is inserted twice with different content,
    it indicates a conflict that must be resolved.
    """


class SolutionRepository:
    """Async repository for PCR reference solution persistence.

    Parameters
    ----------
    db : AsyncIOMotorDatabase
        Tenant-scoped Motor database (``skb_<tenant>``).
    """

    def __init__(self, db: AsyncIOMotorDatabase) -> None:
        self._db = db
        self._solutions = db[SOLUTIONS_COLLECTION]

    # ------------------------------------------------------------------
    # Index management
    # ------------------------------------------------------------------

    async def ensure_indexes(self) -> None:
        """Create required indexes (idempotent).

        Indexes match PCR_EVAL_ENGINE_SPEC Section 7.5:
        - ``{ question_id: 1, version: -1 }`` unique compound
          (supports "get latest version" queries efficiently)
        """
        await self._solutions.create_indexes(
            [
                IndexModel(
                    [("question_id", ASCENDING), ("version", DESCENDING)],
                    unique=True,
                    name="uniq_question_version",
                ),
            ]
        )
        logger.info("Ensured indexes on %s", SOLUTIONS_COLLECTION)

    # ------------------------------------------------------------------
    # Write operations (versioned append)
    # ------------------------------------------------------------------

    async def insert_solution(
        self, doc: Dict[str, Any]
    ) -> tuple[Dict[str, Any], bool]:
        """Persist a new solution version.

        Each ``(question_id, version)`` pair is unique.  Duplicate
        inserts with the same content are idempotent; conflicting
        content raises ``SolutionVersionConflictError``.

        Required fields:
        - ``question_id``
        - ``version`` (int, monotonically increasing per question)
        - ``reference_solution`` (str)
        - ``solution_source`` (``teacher`` or ``llm``)
        - ``model_used`` (str, optional — only for ``llm`` source)

        Returns
        -------
        (document, already_existed)
        """
        question_id = doc["question_id"]
        version = doc["version"]

        doc.setdefault("created_at", datetime.now(timezone.utc))

        try:
            await self._solutions.insert_one(doc)
            logger.info(
                "Persisted solution v%d for question %s (source=%s)",
                version,
                question_id,
                doc.get("solution_source", "unknown"),
            )
            return doc, False
        except DuplicateKeyError:
            existing = await self._solutions.find_one(
                {"question_id": question_id, "version": version}
            )
            if existing is None:
                # Race condition — retry once
                await self._solutions.insert_one(doc)
                return doc, False

            # Verify content consistency on duplicate
            if existing.get("reference_solution") != doc.get(
                "reference_solution"
            ):
                raise SolutionVersionConflictError(
                    f"Solution for question {question_id} version {version} "
                    f"already exists with different content. Increment the "
                    f"version number for a new solution."
                )

            logger.info(
                "Duplicate solution v%d for question %s — idempotent return",
                version,
                question_id,
            )
            return existing, True

    async def upsert_solution(
        self, doc: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Insert a new solution version, auto-incrementing the version.

        This is the primary write path for the
        ``PUT /api/v1/evalpen/solutions/{question_id}`` endpoint.

        If ``version`` is not provided, it is auto-computed as
        ``latest_version + 1`` (or ``1`` if no prior versions exist).

        Returns the persisted document.
        """
        question_id = doc["question_id"]

        if "version" not in doc:
            latest = await self.get_latest_solution(question_id)
            doc["version"] = (latest.get("version", 0) + 1) if latest else 1

        result, _ = await self.insert_solution(doc)
        return result

    # ------------------------------------------------------------------
    # Read operations
    # ------------------------------------------------------------------

    async def get_latest_solution(
        self, question_id: str
    ) -> Optional[Dict[str, Any]]:
        """Fetch the latest (highest version) solution for a question.

        This is the cache lookup path (PCR_EVAL_ENGINE_SPEC Section 5.1).
        If a solution exists, the evaluation engine uses compare-only mode.

        The compound index ``{ question_id: 1, version: -1 }`` makes this
        query efficient — MongoDB can satisfy it from the index alone.
        """
        return await self._solutions.find_one(
            {"question_id": question_id},
            sort=[("version", DESCENDING)],
        )

    async def get_solution_version(
        self, question_id: str, version: int
    ) -> Optional[Dict[str, Any]]:
        """Fetch a specific version of a solution."""
        return await self._solutions.find_one(
            {"question_id": question_id, "version": version}
        )

    async def list_solution_versions(
        self,
        question_id: str,
        *,
        limit: int = 50,
    ) -> List[Dict[str, Any]]:
        """List all solution versions for a question, newest first.

        Useful for auditing solution history and reviewing teacher vs
        LLM-generated solutions.
        """
        cursor = (
            self._solutions.find({"question_id": question_id})
            .sort("version", DESCENDING)
            .limit(limit)
        )
        return await cursor.to_list(length=limit)

    async def has_solution(self, question_id: str) -> bool:
        """Check whether any solution exists for a question.

        This is the fast cache-hit check used by the complexity router
        (PCR_EVAL_ENGINE_SPEC Section 5.2): if a solution exists, route
        to ``cache-hit`` (Haiku-class compare-only); otherwise route to
        the appropriate complexity tier.
        """
        doc = await self._solutions.find_one(
            {"question_id": question_id},
            projection={"_id": 1},
        )
        return doc is not None

    async def get_solutions_by_source(
        self,
        solution_source: str,
        *,
        limit: int = 100,
        skip: int = 0,
    ) -> List[Dict[str, Any]]:
        """Fetch solutions filtered by source (``teacher`` or ``llm``).

        Useful for admin review of LLM-generated solutions.
        """
        cursor = (
            self._solutions.find({"solution_source": solution_source})
            .sort("created_at", DESCENDING)
            .skip(skip)
            .limit(limit)
        )
        return await cursor.to_list(length=limit)
