from dataclasses import dataclass, asdict
from typing import Dict, Any, Optional
from datetime import datetime
import json

@dataclass
class MCQSolution:
    """Data model for MCQ solutions/answers"""
    id: str  # Same as question ID for 1:1 mapping
    question_id: str
    correct_answer: str
    explanation: str
    generated_by: str  # 'database' | 'llm'
    generated_at: str  # ISO format datetime
    llm_model: Optional[str] = None  # Model used if generated by LLM
    confidence_score: Optional[float] = None  # Confidence in solution (0-1)
    validated: bool = False  # Whether solution has been human-validated
    metadata: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for storage"""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'MCQSolution':
        """Create instance from dictionary"""
        return cls(**data)


